sudo: false
language: python
matrix:
  include:
  - python: 3.5
    env: DJANGO_VERSION=2.0.13
  - python: 3.6
    env: DJANGO_VERSION=2.0.13
  - python: 3.7
    env: DJANGO_VERSION=2.0.13

  - python: 3.5
    env: DJANGO_VERSION=2.1.10
  - python: 3.6
    env: DJANGO_VERSION=2.1.10
  - python: 3.7
    env: DJANGO_VERSION=2.1.10

  - python: 3.5
    env: DJANGO_VERSION=2.2.3
  - python: 3.6
    env: DJANGO_VERSION=2.2.3
  - python: 3.7
    env: DJANGO_VERSION=2.2.3

install:
  - "pip install --upgrade pip && pip install -q psycopg2 django==$DJANGO_VERSION"
script:
  - ./setup.py test
before_script:
  - psql -c 'create database "setfield-test";' -U postgres
services:
  - postgresql
